image: debian:sid

variables:
# adjust to your source package
  PKG: screenfetch

stages:
   - build
   - test

package_build:
  stage: build
  script:
    - echo "deb-src http://deb.debian.org/debian sid main" >> /etc/apt/sources.list && apt update -qq && apt build-dep ./ -y -qq
    - apt install -y -qq dpkg-dev && dpkg-buildpackage -us -uc -b && mv ../*.deb ../.changes /tmp
  artifacts:
    paths:
      - /tmp/*.deb
      - /tmp/*.changes

piuparts:
  stage: test
  script:
    - apt update -qq && apt install -y -qq piuparts
    - piuparts --mirror=http://deb.debian.org/debian --logfile=../piuparts.log --fail-on-broken-symlinks /tmp/${PKG}_*.changes
  dependencies:
    - package_build
